---
title: "Developmental Rate Exposure Experimental Design"
output: html_document
---
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

Use the table below or click here for an interactive table: https://bradylab.shinyapps.io/DevRateSaltRandomizedBlock/
```{r make data, echo = F}
set.seed(1)
df <- data.frame(pop = rep(c('cd', 'ca', 'cav', 'a10', 'br', 'l2'), 9, each = 2),
                trt = rep(c('l', 'h'), 18), family = rep(1:3, each = 12), rep = rep(1:3, each = 36), 
                rand = sample(1:108, replace = F), bench = rep(1:3, each = 36))
df$unit <- paste(df$pop, df$family, df$trt, sep = ".")
# order df by bench and rand
df2 <- df[order(df$bench, df$rand),]
# assign position, which will now be random because of previous step 
df2$pos <-rep(1:36, 3)
# set order of levels of trt
df2$trt <- factor(df2$trt, levels = c("l", "m", "h"))
# now reorder df2 by family and treatment so for easier reading
df2 <- df2[order(df2$pop, df2$family, df2$trt),]
# reorder columns for easier reading
df2 <-df2[, c(1,3,2,6,5,7)]
kable(df2)

```